actor_ruc:
- 0968599020001
- 0992339411001
defendant_ruc:
- '1791251237001'
- 0968599020001
elements_by_id:
  actor_input_id: mat-input-1
  defendant_input_id: mat-input-3
elements_by_xpath:
  search_button_xpath: //button[@type="submit"]
  judgement_actions_xpath: //mat-expansion-panel//*[@class="actividad pagina"]/p
  type_process_xpath: //section[@class="filtros-busqueda"]/*[@class="ng-star-inserted"]/strong/text()
  filter_id_xpath: //section[@class="filtros-busqueda"]/*[@class="ng-star-inserted"]/span/text()
  judgement_id_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[1]/span[1]/text()
  date_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[1]/span[2]/text()
  matter_title: //section[@class="header-movimiento ng-star-inserted"]//div[2]/span[1]/text()
  type_action_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[2]/span[2]/text()
  subject_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[3]/span[1]/text()
  judiciary_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[3]/span[2]/text()
  income_type_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[4]/span[1]/text()
  number_process_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[4]/span[2]/text()
  actor_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[5]/span[1]/text()
  defendant_xpath: //section[@class="header-movimiento ng-star-inserted"]//div[5]/span[2]/text()
save_data: data.json
log_message:
  retries_error: 'ERROR: Retries limit exceeded'
  status_code_error: 'ERROR: Status_code'
  timeout_error: 'ERROR: Timeout limit wait exceeded'
scraper:
  retries: 3
  time_load: 25
  time_out_request: 10
  user_agent:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,like
      Gecko) Chrome/124.0.0.0 Safari/537.36
  wait_time: !!python/tuple
  - 1.5
  - 5.5
url: https://procesosjudiciales.funcionjudicial.gob.ec/busqueda-filtros
